// Lista estática dos ativos mais comuns/líquidos da B3, só pra alimentar o
// autocomplete do campo "favoritar ativo" no Mercado ao vivo — não é (nem
// tenta ser) a lista completa de tudo que negocia na bolsa. Digitar
// qualquer outro ticker válido continua funcionando normalmente, essa
// lista só ajuda quem não lembra o código de cor a não digitar tudo.
// classe usa os mesmos valores de CLASSES_ATIVO (só as com cotação
// automática: Ações, FIIs, ETFs).

export interface TickerSugerido {
  ticker: string;
  nome: string;
  classe: "Ações" | "FIIs" | "ETFs";
}

export const TICKERS_B3: TickerSugerido[] = [
  // Ações
  { ticker: "PETR4", nome: "Petrobras PN", classe: "Ações" },
  { ticker: "PETR3", nome: "Petrobras ON", classe: "Ações" },
  { ticker: "VALE3", nome: "Vale ON", classe: "Ações" },
  { ticker: "ITUB4", nome: "Itaú Unibanco PN", classe: "Ações" },
  { ticker: "BBDC4", nome: "Bradesco PN", classe: "Ações" },
  { ticker: "BBDC3", nome: "Bradesco ON", classe: "Ações" },
  { ticker: "BBAS3", nome: "Banco do Brasil ON", classe: "Ações" },
  { ticker: "ABEV3", nome: "Ambev ON", classe: "Ações" },
  { ticker: "WEGE3", nome: "WEG ON", classe: "Ações" },
  { ticker: "RENT3", nome: "Localiza ON", classe: "Ações" },
  { ticker: "RADL3", nome: "Raia Drogasil ON", classe: "Ações" },
  { ticker: "EQTL3", nome: "Equatorial Energia ON", classe: "Ações" },
  { ticker: "SUZB3", nome: "Suzano ON", classe: "Ações" },
  { ticker: "JBSS3", nome: "JBS ON", classe: "Ações" },
  { ticker: "GGBR4", nome: "Gerdau PN", classe: "Ações" },
  { ticker: "CSNA3", nome: "CSN ON", classe: "Ações" },
  { ticker: "CSAN3", nome: "Cosan ON", classe: "Ações" },
  { ticker: "ELET3", nome: "Eletrobras ON", classe: "Ações" },
  { ticker: "ELET6", nome: "Eletrobras PNB", classe: "Ações" },
  { ticker: "ENGI11", nome: "Energisa UNT", classe: "Ações" },
  { ticker: "BBSE3", nome: "BB Seguridade ON", classe: "Ações" },
  { ticker: "B3SA3", nome: "B3 ON", classe: "Ações" },
  { ticker: "ITSA4", nome: "Itaúsa PN", classe: "Ações" },
  { ticker: "MGLU3", nome: "Magazine Luiza ON", classe: "Ações" },
  { ticker: "LREN3", nome: "Lojas Renner ON", classe: "Ações" },
  { ticker: "RAIL3", nome: "Rumo ON", classe: "Ações" },
  { ticker: "VIVT3", nome: "Telefônica Brasil (Vivo) ON", classe: "Ações" },
  { ticker: "TIMS3", nome: "TIM ON", classe: "Ações" },
  { ticker: "SBSP3", nome: "Sabesp ON", classe: "Ações" },
  { ticker: "CPLE6", nome: "Copel PNB", classe: "Ações" },
  { ticker: "CMIG4", nome: "Cemig PN", classe: "Ações" },
  { ticker: "TAEE11", nome: "Taesa UNT", classe: "Ações" },
  { ticker: "EMBR3", nome: "Embraer ON", classe: "Ações" },
  { ticker: "HAPV3", nome: "Hapvida ON", classe: "Ações" },
  { ticker: "RDOR3", nome: "Rede D'Or ON", classe: "Ações" },
  { ticker: "PRIO3", nome: "PRIO ON", classe: "Ações" },
  { ticker: "UGPA3", nome: "Ultrapar ON", classe: "Ações" },
  { ticker: "KLBN11", nome: "Klabin UNT", classe: "Ações" },
  { ticker: "BRFS3", nome: "BRF ON", classe: "Ações" },
  { ticker: "CYRE3", nome: "Cyrela ON", classe: "Ações" },
  { ticker: "MRVE3", nome: "MRV ON", classe: "Ações" },
  { ticker: "EZTC3", nome: "Eztec ON", classe: "Ações" },
  { ticker: "ASAI3", nome: "Assaí ON", classe: "Ações" },
  { ticker: "CRFB3", nome: "Carrefour Brasil ON", classe: "Ações" },
  { ticker: "NTCO3", nome: "Natura &Co ON", classe: "Ações" },
  { ticker: "PCAR3", nome: "Grupo Pão de Açúcar ON", classe: "Ações" },
  { ticker: "GOAU4", nome: "Metalúrgica Gerdau PN", classe: "Ações" },
  { ticker: "USIM5", nome: "Usiminas PNA", classe: "Ações" },
  { ticker: "BRAP4", nome: "Bradespar PN", classe: "Ações" },
  { ticker: "ALPA4", nome: "Alpargatas PN", classe: "Ações" },
  { ticker: "VBBR3", nome: "Vibra Energia ON", classe: "Ações" },
  { ticker: "YDUQ3", nome: "Yduqs ON", classe: "Ações" },
  { ticker: "COGN3", nome: "Cogna ON", classe: "Ações" },
  { ticker: "AZUL4", nome: "Azul PN", classe: "Ações" },
  { ticker: "GOLL4", nome: "Gol PN", classe: "Ações" },
  { ticker: "CVCB3", nome: "CVC ON", classe: "Ações" },
  { ticker: "MULT3", nome: "Multiplan ON", classe: "Ações" },
  { ticker: "ARZZ3", nome: "Arezzo ON", classe: "Ações" },
  { ticker: "SOMA3", nome: "Grupo Soma ON", classe: "Ações" },
  { ticker: "PETZ3", nome: "Petz ON", classe: "Ações" },
  { ticker: "VAMO3", nome: "Vamos ON", classe: "Ações" },
  { ticker: "SLCE3", nome: "SLC Agrícola ON", classe: "Ações" },
  { ticker: "SMTO3", nome: "São Martinho ON", classe: "Ações" },
  { ticker: "JHSF3", nome: "JHSF ON", classe: "Ações" },
  { ticker: "IGTI11", nome: "Iguatemi UNT", classe: "Ações" },
  { ticker: "ODPV3", nome: "Odontoprev ON", classe: "Ações" },
  { ticker: "HYPE3", nome: "Hypera ON", classe: "Ações" },
  { ticker: "FLRY3", nome: "Fleury ON", classe: "Ações" },
  { ticker: "QUAL3", nome: "Qualicorp ON", classe: "Ações" },
  { ticker: "PSSA3", nome: "Porto Seguro ON", classe: "Ações" },
  { ticker: "BPAC11", nome: "BTG Pactual UNT", classe: "Ações" },
  { ticker: "SANB11", nome: "Santander Brasil UNT", classe: "Ações" },
  { ticker: "BPAN4", nome: "Banco Pan PN", classe: "Ações" },
  { ticker: "BEEF3", nome: "Minerva ON", classe: "Ações" },
  { ticker: "MRFG3", nome: "Marfrig ON", classe: "Ações" },
  { ticker: "POMO4", nome: "Marcopolo PN", classe: "Ações" },
  { ticker: "RECV3", nome: "PetroRecôncavo ON", classe: "Ações" },
  { ticker: "ENEV3", nome: "Eneva ON", classe: "Ações" },
  { ticker: "CSMG3", nome: "Copasa ON", classe: "Ações" },
  { ticker: "SAPR11", nome: "Sanepar UNT", classe: "Ações" },
  { ticker: "ALSO3", nome: "Aliansce Sonae ON", classe: "Ações" },
  { ticker: "ANIM3", nome: "Anima Educação ON", classe: "Ações" },
  { ticker: "CASH3", nome: "Méliuz ON", classe: "Ações" },
  { ticker: "DXCO3", nome: "Dexco ON", classe: "Ações" },
  { ticker: "RAPT4", nome: "Randon PN", classe: "Ações" },
  { ticker: "TOTS3", nome: "Totvs ON", classe: "Ações" },
  { ticker: "TRPL4", nome: "Isa Cteep PN", classe: "Ações" },
  { ticker: "WIZC3", nome: "Wiz Co ON", classe: "Ações" },
  { ticker: "STBP3", nome: "Santos Brasil ON", classe: "Ações" },
  { ticker: "TGMA3", nome: "Tegma ON", classe: "Ações" },
  { ticker: "UNIP6", nome: "Unipar PNB", classe: "Ações" },
  { ticker: "SEER3", nome: "Ser Educacional ON", classe: "Ações" },
  { ticker: "LWSA3", nome: "Locaweb ON", classe: "Ações" },
  { ticker: "GMAT3", nome: "Grupo Mateus ON", classe: "Ações" },
  { ticker: "INTB3", nome: "Intelbras ON", classe: "Ações" },
  { ticker: "POSI3", nome: "Positivo ON", classe: "Ações" },
  { ticker: "CBAV3", nome: "CBA ON", classe: "Ações" },
  { ticker: "BRKM5", nome: "Braskem PNA", classe: "Ações" },
  { ticker: "CIEL3", nome: "Cielo ON", classe: "Ações" },
  { ticker: "IRBR3", nome: "IRB Brasil ON", classe: "Ações" },

  // FIIs
  { ticker: "HGLG11", nome: "CSHG Logística", classe: "FIIs" },
  { ticker: "KNRI11", nome: "Kinea Renda Imobiliária", classe: "FIIs" },
  { ticker: "XPML11", nome: "XP Malls", classe: "FIIs" },
  { ticker: "MXRF11", nome: "Maxi Renda", classe: "FIIs" },
  { ticker: "HGRU11", nome: "CSHG Renda Urbana", classe: "FIIs" },
  { ticker: "VISC11", nome: "Vinci Shopping Centers", classe: "FIIs" },
  { ticker: "BCFF11", nome: "BTG Pactual FoF", classe: "FIIs" },
  { ticker: "IRDM11", nome: "Iridium Recebíveis", classe: "FIIs" },
  { ticker: "KNCR11", nome: "Kinea Rendimentos Imobiliários", classe: "FIIs" },
  { ticker: "HGRE11", nome: "CSHG Real Estate", classe: "FIIs" },
  { ticker: "XPLG11", nome: "XP Log", classe: "FIIs" },
  { ticker: "VILG11", nome: "Vinci Logística", classe: "FIIs" },
  { ticker: "RECT11", nome: "UBS (Br) Recebíveis Imobiliários", classe: "FIIs" },
  { ticker: "BTLG11", nome: "BTG Pactual Logística", classe: "FIIs" },
  { ticker: "RBRF11", nome: "RBR Alpha Multiestratégia", classe: "FIIs" },
  { ticker: "HFOF11", nome: "Hedge Top FoFII", classe: "FIIs" },
  { ticker: "ALZR11", nome: "Alianza Trust Renda Imobiliária", classe: "FIIs" },
  { ticker: "BRCO11", nome: "Bresco Logística", classe: "FIIs" },
  { ticker: "VGIR11", nome: "Valora RE III", classe: "FIIs" },
  { ticker: "KFOF11", nome: "Kinea FoF", classe: "FIIs" },
  { ticker: "RBRP11", nome: "RBR Properties", classe: "FIIs" },
  { ticker: "VRTA11", nome: "Fator Verità", classe: "FIIs" },
  { ticker: "CPTS11", nome: "Capitânia Securities II", classe: "FIIs" },
  { ticker: "RECR11", nome: "REC Recebíveis Imobiliários", classe: "FIIs" },
  { ticker: "HGCR11", nome: "CSHG Recebíveis Imobiliários", classe: "FIIs" },
  { ticker: "BTCI11", nome: "BTG Pactual Crédito Imobiliário", classe: "FIIs" },
  { ticker: "VGHF11", nome: "Valora Hedge Fund", classe: "FIIs" },
  { ticker: "KNIP11", nome: "Kinea Índices de Preços", classe: "FIIs" },
  { ticker: "XPCI11", nome: "XP Crédito Imobiliário", classe: "FIIs" },
  { ticker: "MCCI11", nome: "Mérito Desenvolvimento Imobiliário", classe: "FIIs" },
  { ticker: "PVBI11", nome: "VBI Prime Properties", classe: "FIIs" },

  // ETFs
  { ticker: "BOVA11", nome: "iShares Ibovespa", classe: "ETFs" },
  { ticker: "SMAL11", nome: "iShares Small Cap", classe: "ETFs" },
  { ticker: "IVVB11", nome: "iShares S&P 500", classe: "ETFs" },
  { ticker: "BOVV11", nome: "It Now Ibovespa", classe: "ETFs" },
  { ticker: "DIVO11", nome: "It Now IDIV", classe: "ETFs" },
  { ticker: "ECOO11", nome: "It Now ISE", classe: "ETFs" },
  { ticker: "FIND11", nome: "It Now IFNC", classe: "ETFs" },
  { ticker: "GOVE11", nome: "It Now IGCT", classe: "ETFs" },
  { ticker: "SPXI11", nome: "It Now S&P 500", classe: "ETFs" },
  { ticker: "BBSD11", nome: "BB ETF S&P Dividendos Brasil", classe: "ETFs" },
  { ticker: "HASH11", nome: "Hashdex Nasdaq Crypto Index", classe: "ETFs" },
  { ticker: "XINA11", nome: "Trend ETF China", classe: "ETFs" },
  { ticker: "PIBB11", nome: "It Now PIBB IBrX-50", classe: "ETFs" },
  { ticker: "ISUS11", nome: "It Now ISE", classe: "ETFs" },
];
